digibeti/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings

from django.conf.urls.static import static

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('digitalbeti.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digitalbeti/urls.py
from django.contrib.auth import admin
from django.urls import path, re_path

from . import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    path('impact', views.impact, name='impact'),
    path('state-webinar', views.state_webinar, name='state-webinar'),
    path('state-event', views.state_event, name='state-event'),
    path('about-fb', views.about_facebook, name='about-fb'),
    path('about', views.about_project, name='about-project'),
    path('about-csc', views.about_csc, name='about-csc'),
    path('jobs', views.jobs, name='jobs'),
    path('digital-marketing', views.digital_marketing, name='digital-marketing'),
    path('online-safety', views.online_safety, name='online-safety'),

    # AUTH
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('signup', views.user_signup, name='signup'),
    path('reset', views.reset_password, name='reset_password'),

    # VILLAGE DETAILS API
    path('api/vd/districts', views.get_districts_for_state, name='get_district'),
    path('api/vd/cities', views.get_subdistrict_for_state_and_district, name='get_subdistrict'),
    path('api/vd/villages', views.get_village_for_state_and_district_village, name='get_village'),

    # LOGGED IN
    path('dashboard', views.user_dashboard, name='user_dashboard'),
    path('user/curriculum', views.curriculum, name='curriculum'),
    path('user/not-registered', views.not_registerd, name='not_registered'),
    path('user/fill-details', views.beneficiary_details_input, name='fill_details'),
    path('user/exams', views.user_exam, name='exams'),
    path('user/download-certificate/<str:ref_hash>',
         views.UserCertificateView.as_view(), name='user_download_certificate'),
    path('user/download-certificate/<str:ref_hash>',
         views.coming_soon, name='coming_soon'),

    # VLE
    path('vle/overview/<int:user_id>', views.vle_overview, name='vle_overview'),
    path('vle/not-registered', views.vle_not_registerd, name='vle_not_registered'),
    path('vle/fill-details', views.vle_details_input, name='vle_details_input'),
    path('vle/reg_user', views.vle_register_user, name='reg_user'),
    path('vle/reg_user_prompt', views.vle_register_user_prompt, name='reg_user_prompt'),
    path('vle/reg_history', views.vle_reg_history, name='reg_history'),
    path('vle/conduct_exams/<str:ref_hash>', views.conduct_exams, name='conduct_exams'),
    path('vle/completed/<str:ref_hash>', views.completed_exam, name='completed_exam'),
    path('vle/history', views.vle_exams_history, name='history'),
    path('vle/competition', views.vle_competition, name='competition'),
    path('vle/competition_input', views.vle_competition_input, name='vle_competition_input'),
    path('vle/assets', views.vle_assets, name='assets'),
    path('vle/exams', views.vle_user_exam, name='vle_user_exam'),
    path('vle/download-certificate/<str:ref_hash>',
         views.VLECertificateView.as_view(), name='vle_download_certificate'),

    path('dmdc/overview/<str:district>', views.dmdc_overview, name='dmdc_overview'),
    path('dmdc/select-district', views.dmdc_district_input, name='dmdc_district_input'),
    path('dmdc/vles/<str:district>', views.dmdc_all_vle, name='dmdc_all_vle_list'),
    path('dmdc/vles', views.dmdc_all_vle, name='dmdc_all_vle'),
    path('dmdc/top-vles', views.dmdc_top_vle, name='dmdc_top_vle'),

    path('state/overview/<str:state>', views.state_overview, name='state_overview'),
    path('state/districts/<str:state>', views.state_all_districts, name='state_all_districts_list'),
    path('state/districts', views.state_all_districts, name='state_all_districts'),
    path('state/top-vles', views.state_top_vle, name='state_top_vle'),

    path('su/states', views.admin_all_states, name='admin_all_states'),
    path('su/create-user', views.admin_create_user, name='admin_create_user'),
    path('su/create-user-bulk', views.admin_create_user_bulk, name='admin_create_bulk'),
    path('su/all-vles',views.all_vles, name='admin_all_vles'),
    path('su/delete-vle/<str:email>',views.delete_vle, name='admin_delete_vle'),
]

digitalbeti/models.py
from datetime import date

from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
import random, string
from django.utils.translation import gettext_lazy as _

# Create your models here.
from django.forms import ModelForm, RadioSelect, TextInput, Textarea
from bootstrap_datepicker.widgets import DatePicker

STATE_KEY_MAP = {
    'JAMMU AND KASHMIR': 'JK',
    'TELANGANA': 'TS',
    'TAMIL NADU': 'TN',
    'CHHATTISGARH': 'CG',
    'BIHAR': 'BR',
    'UTTAR PRADESH': 'UP',
    'KERALA': 'KL',
    'MAHARASHTRA': 'MH',
    'RAJASTHAN': 'RJ',
    'HARYANA': 'HR',
}


def generate_random_string():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=16))


class CustomValidators:
    @staticmethod
    def validate_date_of_birth(value):
        today = date.today()
        age = today.year - value.year - ((today.month, today.day) < (value.month, value.day))
        if age < 18:
            raise ValidationError('Age needs to be in between 18 and 25 years')


class Address(models.Model):
    STATE_CHOICES = [
        ('JAMMU AND KASHMIR', 'JAMMU AND KASHMIR'),
        ('TELANGANA', 'TELANGANA'),
        ('TAMIL NADU', 'TAMIL NADU'),
        ('CHHATTISGARH', 'CHHATTISGARH'),
        ('BIHAR', 'BIHAR'),
        ('UTTAR PRADESH', 'UTTAR PRADESH'),
        ('KERALA', 'KERALA'),
        ('MAHARASHTRA', 'MAHARASHTRA'),
        ('RAJASTHAN', 'RAJASTHAN'),
        ('HARYANA', 'HARYANA'),
    ]
    state = models.CharField(max_length=100, choices=STATE_CHOICES, verbose_name=_('State'))
    subdistrict = models.CharField(max_length=100, verbose_name=_('Subdistrict'))
    district = models.CharField(max_length=100, verbose_name=_('District'))
    village = models.CharField(max_length=100, verbose_name=_('Village'))
    text = models.CharField(max_length=250, verbose_name='Full Address', blank=True)

    def __str__(self):
        return '%s:%s:%s:%s' % (self.state, self.district, self.subdistrict, self.village)


class DigitalBetiUser(models.Model):
    USER_KINDS = [
        ('USER', 'User'),
        ('VLE', 'Village Level Entrepreneur'),
        ('DM/DC', 'DM/DC'),
        ('STATE', 'States'),
        ('ADMIN', 'Admin'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    kind = models.CharField(max_length=100, choices=USER_KINDS)
    vle = models.ForeignKey('DigitalBetiUser', on_delete=models.SET_NULL, null=True, blank=True)
    last_login_time = models.DateTimeField(auto_now=True)
    creation_time = models.DateTimeField(auto_now_add=True)
    state = models.CharField(choices=Address.STATE_CHOICES, max_length=100, null=True)
    district = models.CharField(max_length=100, null=True, blank=True)
    subdistrict = models.CharField(max_length=100, null=True, blank=True)
    village = models.CharField(max_length=100, null=True, blank=True)
    uk = models.CharField(max_length=24, null=True, blank=True)
    prr = models.BooleanField(default=False)

    def __str__(self):
        return self.kind + ':' + self.user.username

    @classmethod
    def create_if_not_exist(cls, user, vle=None):
        try:
            digital_beti_user = user.digitalbetiuser
        except DigitalBetiUser.DoesNotExist:
            digital_beti_user = DigitalBetiUser()
            digital_beti_user.kind = 'USER'
            digital_beti_user.user = user
            if vle:
                digital_beti_user.vle = vle
            digital_beti_user.save()
        return digital_beti_user

    @property
    def examination_status(self):
        exam_count = Exam.objects.count()
        completed_count = AnswerSet.objects.filter(participant=self, result='SUCCESS').count()
        return '%s of %s' % (completed_count, exam_count)

    def certificate_hash(self):
        exam_count = Exam.objects.count()
        completed_count = AnswerSet.objects.filter(participant=self, result='SUCCESS').count()
        if exam_count == completed_count:
            return ':'.join([a.ref_hash for a in AnswerSet.objects.filter(participant=self, result='SUCCESS')])
        return None


class VillageDetails(models.Model):
    state = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    subdistrict = models.CharField(max_length=100)
    village = models.CharField(max_length=100)

    def __str__(self):
        return '%s:%s:%s:%s' % (self.state, self.district, self.subdistrict, self.village)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['state', 'district', 'subdistrict', 'village'], name='village_detail')
        ]


class BeneficiaryData(models.Model):
    GENDER_CHOICES = [(1, 'Female'), (2, 'Male')]
    EDUCATION_OPTION = [
        ('-10', 'Below 10th'),
        ('10', '10th (High School)'),
        ('12', '12th (Intermediate)'),
        ('G', 'Graduate'),
        ('PG', 'Post Graduate and Above'),
    ]
    ANNUAL_INCOME_LIST = [
        (0, 'Upto 300,000'),
        (1, 'Between 300,000 to 500,000'),
        (2, '500,000+'),
    ]
    MONTHLY_INCOME_LIST = [
        (0, '0-10,000'),
        (1, '10,000-20,000'),
        (2, '20,000+')
    ]
    YES_NO = [(True, 'Yes'), (False, 'No')]
    LANGUAGE_CHOICE = [('NA', 'Not Applicable'),
                       ('Assamese', 'Assamese'),
                       ('Bengali', 'Bengali'),
                       ('Bodo', 'Bodo'),
                       ('Dogri', 'Dogri'),
                       ('Gujarati', 'Gujarati'),
                       ('Hindi', 'Hindi'),
                       ('Kannada', 'Kannada'),
                       ('Kashmiri', 'Kashmiri'),
                       ('Konkani', 'Konkani'),
                       ('Maithili', 'Maithili'),
                       ('Malayalam', 'Malayalam'),
                       ('Manipuri', 'Manipuri'),
                       ('Marathi', 'Marathi'),
                       ('Nepali', 'Nepali'),
                       ('Oriya', 'Oriya'),
                       ('Punjabi', 'Punjabi'),
                       ('Sanskrit', 'Sanskrit'),
                       ('Santhali', 'Santhali'),
                       ('Sindhi', 'Sindhi'),
                       ('Tamil', 'Tamil'),
                       ('Telugu', 'Telugu')]
    user = models.OneToOneField(DigitalBetiUser, models.CASCADE, null=True)
    first_name = models.CharField(max_length=100, verbose_name=_('First name'))
    middle_name = models.CharField(max_length=120, blank=True, verbose_name=_('Middle name'))
    last_name = models.CharField(max_length=120, verbose_name=_('Last name'))
    fathers_name = models.CharField(max_length=120, verbose_name=_('Father name'))
    mothers_name = models.CharField(max_length=120, verbose_name=_('Mother name'))
    gender = models.IntegerField(choices=GENDER_CHOICES, default=1, verbose_name=_('Gender'))
    date_of_birth = models.DateField(validators=[CustomValidators.validate_date_of_birth],verbose_name=_('Date of birth'))
    email_id = models.CharField(max_length=250, null=True, blank=True, verbose_name=_('Email'))
    phone_number = models.CharField(max_length=13, null=True, blank=True, verbose_name=_('Phone Number'))
    personal_monthly_income = models.IntegerField(choices=MONTHLY_INCOME_LIST, default=0,verbose_name=_('Personal monthly income'))
    permanent_address = models.ForeignKey(Address, models.SET_NULL, related_name='permanent', null=True, blank=True)
    language_pref_1 = models.CharField(verbose_name=_('First Language Preference'), max_length=30,
                                       choices=LANGUAGE_CHOICE,
                                       default='Hindi')
    language_pref_2 = models.CharField(verbose_name=_('Second Language Preference'), max_length=30,
                                       choices=LANGUAGE_CHOICE, default='NA')
    language_pref_3 = models.CharField(verbose_name=_('Third Language Preference'), max_length=30,
                                       choices=LANGUAGE_CHOICE,
                                       default='NA')
    education_qualification = models.CharField(max_length=50, choices=EDUCATION_OPTION, default='10+', verbose_name=_('Education qualification'))
    differently_abled = models.BooleanField(verbose_name=_('Are you differently abled?'), default=False, choices=YES_NO)
    bank_account = models.BooleanField(verbose_name=_('Do you have a bank account?'), default=False, choices=YES_NO)
    facebook_link = models.CharField(verbose_name=_('Facebook Profile Link'), max_length=264, null=True, blank=True)
    tc_count = models.IntegerField(verbose_name=_('Number of Training Computers'), default=0)
    vle_csc_id = models.CharField(verbose_name=_('VLE CSC ID'), max_length=20, null=True, blank=True)


class Exam(models.Model):
    title = models.CharField(max_length=100)
    urls = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.title


class Question(models.Model):
    exam = models.ForeignKey(Exam, models.CASCADE)
    option_1 = models.CharField(max_length=1000)
    option_2 = models.CharField(max_length=1000)
    option_3 = models.CharField(max_length=1000)
    option_4 = models.CharField(max_length=1000)
    order = models.IntegerField()
    correct_answer = models.IntegerField()

    def __str__(self):
        str = self.exam.title
        for data in self.questiondata_set.all().order_by('order'):
            str += (' :: ' + data.data)
        return str


class QuestionData(models.Model):
    DATA_TYPE = [
        ('TEXT', 'Text'),
        ('IMAGE', 'Image'),
        ('VIDEO', 'Video'),
    ]
    question = models.ForeignKey(Question, models.CASCADE)
    type = models.CharField(max_length=10, choices=DATA_TYPE)
    data = models.CharField(max_length=1000)
    order = models.IntegerField()


class AnswerSet(models.Model):
    ANSWER_SET_STATUS = [
        ('STARTED', 'Started'),
        ('COMPLETED', 'Completed'),
    ]
    RESULT = [
        ('PENDING', 'Pending'),

digitalbeti/templates/digitalbeti/logged-in/dmdc/all_vles.html
{% extends "digitalbeti/logged-in/dashboard_base.html" %}
{% load static %}

<!-- Title -->
{% block title %}
    VLE Dashboard || Digital Beti
{% endblock title %}

{% block subheader %}
    <!-- Heading -->
    <div class="container-fluid dashboard-header">
        <div class="row justify-content-center align-items-center">
            <div class="col-12">
                <h1 class="text-center">{{ district|title }}, All VLEs</h1>
            </div>
        </div>
    </div>
{% endblock subheader %}

{% block body %}
    <!-- Content -->
    <div class="container py-4">
        <div style="overflow-x:auto">
            <table class="table table-striped mt-2">
                <thead style="background-color: #EDEEF2">
                <tr style="font-weight: bold; text-align: left;">
                    <th scope="col" class="sNo">S. No.</th>
                    <th scope="col" class="appN">Name</th>
                    <th scope="col" class="name">subdistrict</th>
                    <th scope="col" class="staE">Village</th>
                    <th scope="col" class="regC">Registered Users</th>
                </tr>
                </thead>
                <tbody id="VLEDashTBody">
                <!-- Run a for loop here. -->
                {% for vle in vles %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'vle_overview' user_id=vle.id %}">{{ vle.user.first_name }} {{ vle.user.last_name }}</a></td>
                        <td>{{ vle.subdistrict }}</td>
                        <td>{{ vle.village }}</td>
                        <td>{{ vle.digitalbetiuser_set.count }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock body %}


{% block scripttags %}

{% endblock scripttags %}

digitalbeti/templates/digitalbeti/logged-in/dmdc/dmdc_dashboard.html
{% extends "digitalbeti/logged-in/dashboard_base.html" %}
{% load static %}

<!-- Title -->
{% block title %}
    VLE Overview || Digital Beti
{% endblock title %}

{% block subheader %}
    <!-- Heading -->
    <div class="container-fluid dashboard-header">
        <div class="row justify-content-center align-items-center">
            <div class="col-12">
                <h1 class="text-center">{{ district|title }}, {{ state|title }}
                    <span class="text-dark"> Overview</span></h1>
            </div>
        </div>
    </div>
{% endblock subheader %}

{% block body %}

    <!-- Content -->
    <div class="container py-5">
        <div class="row">
            <div class="col-6 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total Subdistricts</h5>
                        <h1>{{ subdistrict_count }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-6 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total Villages</h5>
                        <h1>{{ village_count }}</h1>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-3 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total VLEs</h5>
                        <a href="{% url 'dmdc_all_vle_list' district=district %}"><h1>{{ vle_count }}</h1></a>
                    </div>
                </div>
            </div>
            <div class="col-3 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total Enrolled</h5>
                        <h1>{{ total_registered }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-3 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total Users Who Gave Exam</h5>
                        <h1>{{ total_exams_given }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-3 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total Users Passed</h5>
                        <h1>{{ total_passed }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-3 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Total Users Failed</h5>
                        <h1>{{ total_failed }}</h1>
                    </div>
                </div>
            </div>
            <div class="col-6 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-between">
                        <h5 class="card-title">Result</h5>
                        <canvas id="success_chart"></canvas>
                    </div>
                </div>
            </div>
            <div class="col-3 my-2">
                <div class="card h-100">
                    <div class="card-body d-flex flex-column justify-content-top">
                        <h5 class="card-title">Top VLEs</h5>
                        {% for vle in top_vle %}
                            <p>{{ forloop.counter }}. <a href="{% url 'vle_overview' user_id=vle.id %}">{{ vle.user.first_name }} {{ vle.user.last_name }}</a></p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}


{% block scripttags %}
    <script type="text/javascript">
        var ctx = document.getElementById('success_chart');
        new Chart(ctx, {
            type: 'doughnut',
            data: {
                labels: ['Passed', 'Failed'],
                datasets: [
                    {
                        label: '# of Votes',
                        data: [{{total_passed}}, {{total_failed}}],
                        backgroundColor: [
                            '#0183FB',
                            '#00227C'
                        ],
                        borderColor: [
                            '#0183FB',
                            '#00227C'
                        ],
                        borderWidth: 1
                    }]
            },
            {#optio ns: options#}
        });
    </script>
{% endblock scripttags %}

digitalbeti/templates/digitalbeti/logged-in/dmdc/dmdc_district_input.html
{% extends 'digitalbeti/logged-in/dashboard_base.html' %}
{% load static %}
<!-- Title -->
{% block title %}
    Fill Form || Digital Beti
{% endblock title %}

{% load crispy_forms_tags %}

{% block body %}

    <!-- Form -->
    <div class="container py-5">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{ form.state|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    {{ form.district|as_crispy_field }}
                </div>
            </div>
            <div class="text-left">
                <button type="submit" class="btn btn-orange">Save Details</button>
            </div>
        </form>
    </div>

{% endblock body %}


{% block scripttags %}
    <script src="{% static "digitalbeti/js/address-form.js" %}"></script>
{% endblock scripttags %}

digitalbeti/templates/digitalbeti/logged-in/dmdc/top_users.html
{% extends "digitalbeti/logged-in/dashboard_base.html" %}
{% load static %}

<!-- Title -->
{% block title %}
    VLE Dashboard || Digital Beti
{% endblock title %}

{% block subheader %}
    <!-- Heading -->
    <div class="container-fluid dashboard-header">
        <div class="row justify-content-center align-items-center">
            <div class="col-12">
                <h1 class="text-center">{{ district|title }}, <span class="text-dark"> Top VLEs</span></h1>
            </div>
        </div>
    </div>
{% endblock subheader %}

{% block body %}
    <!-- Content -->
    <div class="container py-4">
        <div style="overflow-x:auto">
            <table class="table table-striped mt-2">
                <thead style="background-color: #EDEEF2">
                <tr style="font-weight: bold; text-align: left;">
                    <th scope="col" class="sNo">S. No.</th>
                    <th scope="col" class="appN">Name</th>
                    <th scope="col" class="name">subdistrict</th>
                    <th scope="col" class="staE">Village</th>
                    <th scope="col" class="regC">Registered Users</th>
                </tr>
                </thead>
                <tbody id="VLEDashTBody">
                <!-- Run a for loop here. -->
                {% for vle in vles %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td><a href="{% url 'vle_overview' user_id=vle.id %}">{{ vle.user.first_name }} {{ vle.user.last_name }}</a></td>
                        <td>{{ vle.subdistrict }}</td>
                        <td>{{ vle.village }}</td>
                        <td>{{ vle.digitalbetiuser_set.count }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock body %}


{% block scripttags %}

{% endblock scripttags %}